name: Docs v2 Feedback Form
description: Use this form to give us feedback on Docs v2
title: '[Docs-V2-Feedback]'
labels:
  - docs-v2-feedback
assignees:
  - melpadden
  - sczembor
  - dylanireland
body:
  - type: markdown
    attributes:
      value: |
        This is a feedback form
  - type: dropdown
    id: type
    attributes:
      label: Category
      description: Please choose the category that best describes your needs.
      options:
        - Error
        - Enhancement
        - Missing Content
        - Other
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      placeholder: john@doe.com
    validations:
      required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      placeholder: Please describe your issue here.
      description: Please provide a detailed description of your issue.
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments (optional)
      description: Please attach any logs, screenshots, or links that may help with the analysis.
    validations:
      required: false