name: build
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            selected_node_version:
                required: true
                type: string
            base_url:
                required: true
                type: string
            site_url:
                required: true
                type: string
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ inputs.selected_node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.selected_node_version }}
          cache: yarn

      - name: Template credentials - production
        if: github.ref == 'refs/heads/main'
        uses: cuchi/jinja2-action@1149b92d9ea6db61d7f71c22e3d5028d8065f140
        with:
          template: .github/templates/.env.production.j2
          output_file: .env.production
        env:
          ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
          ALGOLIA_INDEX_NAME: ${{ vars.ALGOLIA_INDEX_NAME }}
          ALGOLIA_API_KEY: ${{ vars.ALGOLIA_API_KEY }}
          CROWDIN_PERSONAL_ACCESS_TOKEN: ""
          GOOGLE_TAG_ANONYMIZE_IP: ${{ vars.GOOGLE_TAG_ANONYMIZE_IP }}
          GOOGLE_TAG_TRACKING_ID: ${{ vars.GOOGLE_TAG_TRACKING_ID }}
          GOOGLE_TAG_MANAGER_ID: ${{ vars.GOOGLE_TAG_MANAGER_ID }}
          DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
          DIRECTUS_GRAPHQL_URL: ${{ secrets.DIRECTUS_GRAPHQL_URL }}
          DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
          SITE_URL: ${{ vars.SITE_URL }}
          ALGOLIA_SITE_APP_ID: ${{ vars.ALGOLIA_SITE_APP_ID }}
          ALGOLIA_SITE_API_KEY: ${{ vars.ALGOLIA_SITE_API_KEY }}
          ALGOLIA_SITE_INDEX_NAME: ${{ vars.ALGOLIA_SITE_INDEX_NAME }}
          BASE_URL: ${{ inputs.base_url }}

      - name: Template credentials - preview
        if: github.event_name == 'pull_request'
        uses: cuchi/jinja2-action@1149b92d9ea6db61d7f71c22e3d5028d8065f140
        with:
          template: .github/templates/.env.production.j2
          output_file: .env.production
        env:
          DIRECTUS_URL: ${{ secrets.PREVIEW_DIRECTUS_URL }}
          DIRECTUS_GRAPHQL_URL: ${{ secrets.PREVIEW_DIRECTUS_GRAPHQL_URL }}
          DIRECTUS_TOKEN: ${{ secrets.PREVIEW_DIRECTUS_TOKEN }}
          SITE_URL: ${{ inputs.site_url }}
          BASE_URL: ${{ inputs.base_url }}

      - name: Yarn install
        run: |
          yarn install

      - name: Run code analysis
        run: |
          yarn format

      - name: Clear Docusaurus cache
        run: |
          yarn clear

      - name: Build app
        run: |
          yarn build --out-dir ./docs
        env:
          NODE_ENV: production

      - name: Add CNAME file to the build output payload to keep the custom domain settings of GitHub Pages enabled
        run: |
          echo "$prod_pages_fqdn" > ./docs/CNAME

      - uses: actions/upload-artifact@v4
        with:
          name: gh-pages-depl-payload
          path: ./docs
