name: Validate External Links
on:
    workflow_call:
        inputs:
            working_directory:
                required: true
                type: string

jobs:
    rollback-if-tests-fail-prod:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@master
                with:
                    name: gh-pages-backup
                    path: ${{ inputs.working_directory }}

            - name: Deploy the previous version to Github Pages
                uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir:  ${{ inputs.working_directory }}
