name: Validate External Links
on:
    workflow_call:
        inputs:
            working_directory:
                required: true
                type: string

jobs:
    validate-external-links:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ env.selected_node_version }}
            uses: actions/setup-node@v3
            with:
                node-version: ${{ env.selected_node_version }}
                cache: yarn

            - name: Yarn install
            run: |
                yarn install

            - name: Validate external links
            run: |
                cd cspr-docs && yarn check:externals
