name: Deploy to Production
on:
    workflow_call:
        inputs:
            working_directory:
                required: true
                type: string

jobs:
    deploy-prod:
        needs: [backup, system-tests-predeployment]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@master
              with:
                  name: gh-pages-depl-payload
                  path:  ${{ inputs.working_directory }}

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir:  ${{ inputs.working_directory }}

            - name: Wait some time to make sure deployment is finished
              run: |
                  sleep 60