name: system-tests-postdeployment-prod
on:
    workflow_call:
        inputs:
            prod_pages_fqdn:
                required: true
                type: string
jobs:

    system-tests-postdeployment-prod:
        runs-on: ubuntu-latest

        steps:
            - name: Test home page
            run: |
                echo "Testing if homepage responds correctly"
                curl --fail https://$prod_pages_fqdn
            - name: Test a random page
            run: |
                echo "Testing if a page responds correctly"
                curl --fail https://$prod_pages_fqdn/operators/setup-network/chain-spec
            - name: Test another random page
            run: |
                echo "Testing if a page responds correctly"
                curl --fail https://$prod_pages_fqdn/concepts/serialization-standard